[package]
name = "lava_torrent"
version = "0.5.0"
authors = ["ttlajus <40629580+ttlajus@users.noreply.github.com>"]
description = "A library for parsing/encoding bencode and .torrent files."
repository = "https://github.com/ttlajus/lava_torrent"
readme = "README.md"
keywords = ["bittorrent", "bencode"]
categories = ["parsing", "encoding"]
license = "MIT OR Apache-2.0"

[badges]
travis-ci = { repository = "ttlajus/lava_torrent" }
codecov = { repository = "ttlajus/lava_torrent" }

[dependencies]
itertools = "0.9.0"
unicode-normalization = "0.1.8"
conv = "0.3.3"
sha-1 = "0.8.2"
error-chain = "0.12.1"
percent-encoding = "2.1.0"

[dev-dependencies]
rand = "0.7.2"
